apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: tp
  name: secret-reader-binding  # Nom du RoleBinding
subjects:
  - kind: ServiceAccount       # Associe le rôle à un ServiceAccount
    name: python-serviceaccount # Nom du ServiceAccount
    namespace: tp     
  - kind: User
    name: user1         
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader-role     # Référence au rôle défini précédemment