apiVersion: v1
kind: Pod
metadata:
  name: python-pod-emptydir
  namespace: tp
spec:
  containers:
    - name: python-container
      image: python_container:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 600Mi
          cpu: 1
        requests:
          memory: 400Mi
          cpu: 200m
      volumeMounts:
        - name: shared-volume
          mountPath: /data
    - name: volume_container
      image: volume_container:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 500Mi
          cpu: 2
        requests:
          memory: 300Mi
          cpu: 400m
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  volumes:
    - name: shared-volume
      emptyDir: {}
