apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  namespace: tp
spec:
  containers:
    - name: python-container
      image: python_container:v2.0
      imagePullPolicy: Never
      resources:
        limits:
          memory: 600Mi
          cpu: 1
        requests:
          memory: 400Mi
          cpu: 200m
    - name: volume-container 
      image: volume_container:v1.0
      imagePullPolicy: Never
      resources:
        limits:
          memory: 500Mi
          cpu: 400m
        requests:
          memory: 300Mi
          cpu: 400m
