apiVersion: apps/v1  # Spécifie la version de l'API pour les objets StatefulSet.
kind: StatefulSet  # Indique que cette ressource est un StatefulSet.
metadata:
  name: python-pod-statefulset  # Nom unique pour identifier ce StatefulSet.
  namespace: tp  # Namespace dans lequel le StatefulSet sera créé.
spec:
  serviceName: "python-service"  # Nom du service associé pour gérer l'accès aux Pods.
  selector:  # Critères pour sélectionner les Pods gérés par ce StatefulSet.
    matchLabels:
      app: python-pod  # Label utilisé pour associer les Pods au StatefulSet.
  template:  # Modèle utilisé pour créer les Pods.
    metadata:
      labels:
        app: python-pod  # Label appliqué aux Pods créés par ce StatefulSet.
    spec:
      containers:  # Liste des conteneurs à exécuter dans chaque Pod.
        - name: python-container  # Nom du premier conteneur.
          image: python_container:v2.0  # Image Docker utilisée pour ce conteneur.
          imagePullPolicy: Never  # Ne jamais récupérer l'image, utiliser l'image locale.
          resources:
            limits:  # Ressources maximales allouées pour ce conteneur.
              memory: 600Mi  
              cpu: 1  
            requests:  # Ressources minimales garanties pour ce conteneur.
              memory: 400Mi  # Mémoire minimale demandée.
              cpu: 200m  # CPU minimale demandée (200 milli-cores).
        - name: volume-container 
          image: volume_container:v1.0
          imagePullPolicy: Never  
          resources:
            limits:  
              memory: 500Mi  
              cpu: 400m  
            requests:  
              memory: 300Mi  
              cpu: 400m  
  volumeClaimTemplates:  # Définition des volumes persistants nécessaires pour chaque Pod.
    - metadata:
        name: python-data  # Nom du volume à créer pour chaque Pod.
      spec:
        accessModes: ["ReadWriteOnce"]  # Mode d'accès du volume (lecture/écriture par un seul Pod).
        resources:
          requests:
            storage: 1Gi  # Demande de stockage de 1 Go pour chaque volume.
