apiVersion: v1
kind: Pod
metadata:
  name: pod-with-labels
  namespace: tp
  labels:
    app: my-app-to-test-services
    tier: frontend
    env: production
spec:
  containers:
    - name: python-container
      image: python_container:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 600Mi
          cpu: 1
        requests:
          memory: 400Mi
          cpu: 200m
    - name: volume-container 
      image: volume_container:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 500Mi
          cpu: 400m
        requests:
          memory: 300Mi
          cpu: 400m
