apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: tp
  labels:
    app: my-app-to-test-services
spec:
  selector:
    app: my-app-to-test-services
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
