apiVersion: apps/v1  # Spécifie la version de l'API pour les objets Deployment.
kind: Deployment  # Indique que cette ressource est un Deployment.
metadata:
  name: deployment-with-labels  # Nom unique pour identifier ce Deployment.
spec:
  selector:  # Critères pour sélectionner les Pods gérés par ce Deployment.
    matchLabels:
      app: python-pod  # Label utilisé pour associer les Pods au Deployment.
  template:  # Modèle utilisé pour créer les Pods.
    metadata:
      labels:
        app: python-pod  # Label appliqué aux Pods créés par ce Deployment.
        dev: prod  # Nouveau label ajouté.
    spec:
      containers:  # Liste des conteneurs à exécuter dans chaque Pod.
        - name: python-container  # Nom du premier conteneur.
          image: python_container:latest  # Image Docker utilisée pour ce conteneur.
          imagePullPolicy: Never  # Ne jamais récupérer l'image, utiliser l'image locale.
          resources:
            limits:  # Ressources maximales allouées pour ce conteneur.
              memory: 600Mi  
              cpu: 1  
            requests:  # Ressources minimales garanties pour ce conteneur.
              memory: 400Mi  
              cpu: 200m  
        - name: volume-container  
          image: volume_container:latest  
          imagePullPolicy: Never  
          resources:
            limits:  
              memory: 500Mi  
              cpu: 400m  
            requests:  
              memory: 300Mi  
              cpu: 400m  
