apiVersion: v1
kind: Pod
metadata:
  name: python-pod-pvc
  namespace: tp
spec:
  containers:
    - name: python-container
      image: python_container:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 600Mi
          cpu: 1
        requests:
          memory: 400Mi
          cpu: 200m
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
    - name: volume-container
      image: volume_container:latest
      imagePullPolicy: Never
      resources:
        limits:
          memory: 500Mi
          cpu: 400m
        requests:
          memory: 300Mi
          cpu: 400m
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: my-pvc
